// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OilfieldManager.Infrastructure.Data;

#nullable disable

namespace OilfieldManager.Infrastructure.Migrations
{
    [DbContext(typeof(OilfieldDbContext))]
    partial class OilfieldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OilfieldManager.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentWellId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWellId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("OilfieldManager.Domain.Entities.WellSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LeaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("WellName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WellSites");
                });

            modelBuilder.Entity("OilfieldManager.Domain.Entities.Asset", b =>
                {
                    b.HasOne("OilfieldManager.Domain.Entities.WellSite", "CurrentWell")
                        .WithMany("DeployedAssets")
                        .HasForeignKey("CurrentWellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentWell");
                });

            modelBuilder.Entity("OilfieldManager.Domain.Entities.WellSite", b =>
                {
                    b.Navigation("DeployedAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
